config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  get 'places/index'
  devise_for :accounts
  get 'home/index'
  root 'home#index'
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bnb.rb
class Bnb < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def index
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
  end
  
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/age_helper.rb
module AgeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/about/index.html.erb
<div class="firstsection">
  <h1>This will be the "about us" section</h1>
</div>

app/views/home/index.html.erb
<!--This homepage is the static page when 
    a user is not logged in-->

<!--Hero section-->

<section class="hero">
  <% if account_signed_in? %>
    <div class="hero-box">
      <div class="hero-content">
        <h1>CannaBnb</h1>
        <h3>Wake up and smell the <span class="green">green</span></h3> 
      </div>
      <br>
      <br>
      <div class="searchbar-box">
        <span class="fa fa-search searchbar-feedback">
          <input type="text" class="searchbar" placeholder="Find a CannaBnb">
            <div class="searchbar-box-append">
              <button class="btn btn-secondary" type="button">
                <i class="fa fa-search"></i>
              </button>
            </div>
        </span>
      </div>
    </div>
    <div class="">
  <% else %>
    <div class="hero-box">
      <div class="hero-content">
        <h1>CannaBnb</h1>
        <h3>Wake up and smell the <span class="green">green</span>.</h3>
        <br>
        <%= button_to "About", about_index_path, class: "about_button", :method => "get" %>
      </div>
    </div>
  <% end %>
  
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CanaBnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <!--Navbar-->

<header>
  
  <h1 class="title">
    <%= link_to 'CannaBnb', home_index_path, class: 'title-link' %>
  </h1>
 
  <input type="checkbox" class="nav-toggle" id="nav-toggle">

  <nav>
    <ul>
      <% if account_signed_in? %>
        <li class="navitem" id="getsborder">
          <%= link_to 'Home', home_index_path, class: "navlink" %>
        </li>
        <li class="navitem" id="getsborder">
          <%= link_to 'Browse', places_index_path, class: "navlink" %>
        </li>
        <!-- <li class="navitem" id="getsborder">
          <%= link_to 'Become a host', class: "navlink" %>
        </li> -->
        <li class="navitem" id="getsborder">
          <%= link_to 'About', about_index_path, class: "navlink" %>
        </li>
        <li class="navitem">
          <%= link_to 'Sign out', destroy_account_session_path, method: :delete, class: "navlink" %>
        </li>
      <% else %>
        <li class="navitem" id="joinus">
          <%= link_to 'Join us!', new_account_registration_path, class: "navlink"%>
        </li>
        <li class="navitem">
          <%= link_to 'Log in', new_account_session_path, class: "navlink", id: "login" %>
        </li>
      <% end %>
    </ul>
  </nav>

  <label for="nav-toggle" class="nav-toggle-label">
    <span>X</span>
  </label>

</header>

<!-- <% if notice.present? %>
  <p class="alert alert-info"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %> -->

    <%= yield %>
    
  </body>
</html>

app/views/places/index.html.erb
<div class="firstsection">
  <h1>This will be the places index!</h1>
</div>